pipeline {
    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                sh '''
                    echo "Checking workspace..."
                    pwd
                    ls -la

                    echo "Marking Jenkins workspace as safe for Git..."
                    git config --global --add safe.directory "${WORKSPACE}"

                    echo "Checking Git..."
                    git status
                '''
            }
        }

        stage('Build and Test') {
            steps {
                sh '''
                    cd spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        cd spring-boot-app

                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                            -Dsonar.projectKey=my-ec2-project \
                            -Dsonar.projectName="Spring Boot App" \
                            -Dsonar.host.url=$SONAR_HOST_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "fathimazahra7907/spring-boot-app:${BUILD_NUMBER}"
            }

            steps {
                script {
                    sh '''
                        cd spring-boot-app
                        docker build -t ${DOCKER_IMAGE} .
                    '''

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'docker-cred'
                    ) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "java-maven-sonar-argocd"
                GIT_USER_NAME = "fathimazahra9562"
            }

            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'git-hub',
                        usernameVariable: 'GITHUB_USERNAME',
                        passwordVariable: 'GITHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        echo "Cleaning old repository..."
                        rm -rf repo-temp

                        echo "Cloning GitHub repository..."

                        git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git repo-temp

                        cd repo-temp

                        echo "Configuring Git..."

                        git config user.email "fathimazahra9562@gmail.com"
                        git config user.name "${GIT_USER_NAME}"

                        echo "Updating deployment image..."

                        sed -i "s|image: .*|image: fathimazahra7907/spring-boot-app:${BUILD_NUMBER}|g" \
                            spring-boot-app-manifests/deployment.yml

                        echo "Updated deployment file:"
                        cat spring-boot-app-manifests/deployment.yml

                        echo "Adding deployment file..."

                        git add spring-boot-app-manifests/deployment.yml

                        echo "Committing changes..."

                        git commit \
                            -m "Update spring boot image tag to ${BUILD_NUMBER} [skip ci]" \
                            || echo "No changes to commit"

                        echo "Pulling latest changes..."

                        git pull --rebase origin main

                        echo "Pushing changes to GitHub..."

                        git push origin main

                        echo "Deployment file updated successfully!"
                    '''
                }
            }
        }
    }
}
